### ISSUE TITLE
Css code errors

### ISSUE THREAD

**Issue by Lutrian1** [Sidopjescherm/your-tribe-squad-page#26]
<img width="1262" alt="image" src="https://github.com/user-attachments/assets/d0641e86-1cd1-487b-b491-67c7478f8b19">

**Comment by Felipe-Rafael-Rosa** [comment]
install this
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive

**Comment by Lutrian1** [comment]
<img width="742" alt="image" src="https://github.com/user-attachments/assets/9fe62fac-7df2-4238-8b13-412d41b80f87">

fixed the other erros. This image says its because the validator doesnt recognize these properties because its new.
