### ISSUE TITLE
Prototypes figma 

### ISSUE THREAD

**Issue by Sebastiaan-hva** [Sidopjescherm/your-tribe-squad-page#9]
sebas:
![image](https://github.com/user-attachments/assets/18301aca-e711-4400-9c05-44f67a50f246)
![image](https://github.com/user-attachments/assets/fde0b100-8701-4039-a519-94f2c2989ab7)
![image](https://github.com/user-attachments/assets/2d07027c-a546-4957-8fbe-055d3874eb7b)

Sidney:
![Desktop prototype 1](https://github.com/user-attachments/assets/d580ce9e-1dd7-4ae3-8231-9ba90c102115)
![Prototype 1](https://github.com/user-attachments/assets/4384eebc-505d-4fed-ad61-c21740913a32)
![Prototype 2](https://github.com/user-attachments/assets/d231d243-c575-4aab-ba56-664e763c7b61)
![Prototype 3](https://github.com/user-attachments/assets/3ed64aef-9f2f-42c1-9195-09f785863a3f)
![Unfinished Prototype Desktop](https://github.com/user-attachments/assets/ee7ae4f1-52fb-49bc-b8a1-2d8796903b8c)

**Comment by Sidopjescherm** [comment]
Hier nog de breakdown schets van onze desktop versie

![Pagina 1 breakdown](https://github.com/user-attachments/assets/7d039746-6279-4039-be81-535271cfd9aa)
![Pagina 2 breakdown](https://github.com/user-attachments/assets/e40fa920-1437-4312-8a51-8582dec9f000)
![Pagina 3 breakdown](https://github.com/user-attachments/assets/c1a227d2-1e5d-42bf-a19b-0010b856b7ed)

**Comment by Lutrian1** [comment]
Een aantal keuzes voor hierarchie:

- Ons team groot en wit, met een blauwe donkere achtergrond. Dit zorgt evoor dat je het belangrijkste als eerste leest. Het amsterdam logo is zwart, op een donkere achtergrond omdat deze niet van belang is. Je ogen gaan eerst naar de grote witte tekst.
- Alles bevind zich in rows en collumns.
- Onze 3 teamleaden staan bovenaan met sebas net wat hoger dan de andere 2. Dit heeft te maken met vorm in de hierarchie.
- De tekst "onze sqaud" is donker paars op een lichte achtergrond, dit is zodat je het toch kan lezen maar het niet teveel op valt. Je leest dit pas nadat je de bovenste dingen heb gezien.
- De achtergrond bij onze 3 namen is om onderscheid te maken/ Contrast.
- De tekst op de laatse pagina staat schuin, zodat het niet opvalt, dit lees je pas stukken later.
- Belangrijkste tekst is ons campus, voor de hierarchie is deze het grootst.
- De tekst ernaast is ongeveer dezelfde kleur als de achtergrond, ook is dit kleiner. Dit doen we zodat we onderscheid maken tussen het belangrijke 'ons campus' en daarna pas lees je waar je ons vaak kunt vinden.

**Comment by Lutrian1** [comment]
![Telefoon Variatie 1](https://github.com/user-attachments/assets/99fa6322-d1e8-49dd-825e-67ef9a1e93e7)
![Telefoon Variatie 2](https://github.com/user-attachments/assets/bbaca2a8-e586-4ab9-9783-307034c72ee7)
![Telefoon Variatie 3](https://github.com/user-attachments/assets/0320dc91-bc7c-47f7-8fc9-411172d806c8)
